In [2]:
import pandas as pd
import numpy as np
import re
import lxml
import csv
import matplotlib

from bs4 import BeautifulSoup
from requests import get

In [10]:
newimdbdata = pd.read_csv('imdbdatafinal.csv')

In [13]:
def number_of_reviews(suburl):
    try:
        subpage = get(suburl)
        subsoup = BeautifulSoup(subpage.content, 'lxml')
        content = subsoup.find(id="main_top")
        titleReviewBar = content.find('div', class_ = 'titleReviewBar')
        titleReviewBarItem = titleReviewBar.find('div', class_ = 'titleReviewBarItem titleReviewbarItemBorder')
        trb = titleReviewBarItem.find('span', class_ = 'subText').text
        semifinal = trb.split('\n')[1]
        final = semifinal.split(' ')[0]
        return final
    except:
        return None

In [16]:
numberreviews=[]
for url in newimdbdata['urls']:
    numberreviews.append(number_of_reviews(url))

In [18]:
newimdbdata['no. of reviews'] = numberreviews

In [19]:
newimdbdata.head()

,title,date,runtime,genre,rating,description,director,stars,votes,gross,budget,urls,Budget $(mil),Gross $(mil),no. of reviews
0,Joker,2019,122,"Crime,Drama,Thriller",8.5,"In Gotham City, mentally troubled comedian...",Todd Phillips,"Joaquin Phoenix, Robert De Niro, Zazie Beetz, ...",763252,$335.45M,55000000,https://www.imdb.com/title/tt7286456/,55.0,335.45,"10,002"
1,Avengers: Endgame,2019,181,"Action,Adventure,Drama",8.4,After the devastating events of Avengers: ...,"Directors:Anthony Russo, Joe Russo","Robert Downey Jr., Chris Evans, Mark Ruffalo, ...",702524,$858.37M,356000000,https://www.imdb.com/title/tt4154796/,356.0,858.37,"8,705"
2,Once Upon a Time... in Hollywood,2019,161,"Comedy,Drama",7.7,A faded television actor and his stunt dou...,Quentin Tarantino,"Leonardo DiCaprio, Brad Pitt, Margot Robbie, E...",446250,$142.50M,90000000,https://www.imdb.com/title/tt7131622/,90.0,142.50,"4,907"
3,Captain Marvel,2019,123,"Action,Adventure,Sci-Fi",6.9,Carol Danvers becomes one of the universe'...,"Directors:Anna Boden, Ryan Fleck","Brie Larson, Samuel L. Jackson, Ben Mendelsohn...",407176,$426.83M,160000000,https://www.imdb.com/title/tt4154664/,160.0,426.83,"7,149"
4,Gisaengchung,2019,132,"Comedy,Drama,Thriller",8.6,Greed and class discrimination threaten th...,Bong Joon Ho,"Kang-ho Song, Sun-kyun Lee, Yeo-jeong Jo, Woo-...",378133,$53.37M,11400000,https://www.imdb.com/title/tt6751668/,11.4,53.37,"2,355"

In [20]:
newimdbdata.to_csv('newimdbdata.csv',index=False)

## Read in filtered movied > 500 reviews

In [6]:
filteredimdbdata = pd.read_csv('filteredimdbdata.csv')

In [11]:
review_tail = 'reviews?ref_=tt_urv'

In [24]:
newurldf = pd.DataFrame({'urls':filteredimdbdata['urls'].copy()})

In [33]:
len(newurldf)

150

In [34]:
reviewurls = []
for url in newurldf['urls']:
    complete_url=url+review_tail
    reviewurls.append(complete_url)

In [48]:
filteredimdbdata['reviewurls']=reviewurls

In [49]:
filteredimdbdata.head()

,title,date,runtime,genre,rating,description,director,stars,votes,gross,budget,urls,Budget $(mil),Gross $(mil),no. of reviews,reviewurls
0,Joker,2019,122,"Crime,Drama,Thriller",8.5,"In Gotham City, mentally troubled comedian...",Todd Phillips,"Joaquin Phoenix, Robert De Niro, Zazie Beetz, ...",763252,$335.45M,55000000,https://www.imdb.com/title/tt7286456/,55.0,335.45,"10,002",https://www.imdb.com/title/tt7286456/reviews?r...
1,Avengers: Endgame,2019,181,"Action,Adventure,Drama",8.4,After the devastating events of Avengers: ...,"Directors:Anthony Russo, Joe Russo","Robert Downey Jr., Chris Evans, Mark Ruffalo, ...",702524,$858.37M,356000000,https://www.imdb.com/title/tt4154796/,356.0,858.37,"8,705",https://www.imdb.com/title/tt4154796/reviews?r...
2,Captain Marvel,2019,123,"Action,Adventure,Sci-Fi",6.9,Carol Danvers becomes one of the universe'...,"Directors:Anna Boden, Ryan Fleck","Brie Larson, Samuel L. Jackson, Ben Mendelsohn...",407176,$426.83M,160000000,https://www.imdb.com/title/tt4154664/,160.0,426.83,"7,149",https://www.imdb.com/title/tt4154664/reviews?r...
3,Star Wars: Episode VIII - The Last Jedi,2017,152,"Action,Adventure,Fantasy",7.0,Rey develops her newly discovered abilitie...,Rian Johnson,"Daisy Ridley, John Boyega, Mark Hamill, Carrie...",533541,$620.18M,317000000,https://www.imdb.com/title/tt2527336/,317.0,620.18,"6,637",https://www.imdb.com/title/tt2527336/reviews?r...
4,Once Upon a Time... in Hollywood,2019,161,"Comedy,Drama",7.7,A faded television actor and his stunt dou...,Quentin Tarantino,"Leonardo DiCaprio, Brad Pitt, Margot Robbie, E...",446250,$142.50M,90000000,https://www.imdb.com/title/tt7131622/,90.0,142.50,"4,907",https://www.imdb.com/title/tt7131622/reviews?r...

In [66]:
def reviews(url):
    response_reviews = get(url)
    reviews_soup = BeautifulSoup(response_reviews.text, 'html.parser')
    # Searching all reviews
    reviews_containers = reviews_soup.find_all('div', class_ = 'imdb-user-review')
    # Looping through each review and extracting title and body
    movie_name = []
    review_titles = []
    review_content = []
    reviewer_name = []
    review_date = []
    feedback = []
    movienamecontent = reviews_soup.find(id="main")
    movienamebox = movienamecontent.find('div', class_='subpage_title_block__right-column')
    moviename = movienamebox.find('a').text
    for review_container in reviews_containers:
        movie_name.append(moviename)
        review_title = review_container.find('a', class_ = 'title').text.strip()
        review_body = review_container.find('div', class_ = 'text').text.strip()
        review_titles.append(review_title)
        review_content.append(review_body)
        review_name = review_container.find('span', class_ = 'display-name-link')
        reviewer_name.append(review_name.find("a").text)
        date_of_review = review_container.find('span', class_ = 'review-date').text.strip()
        review_date.append(date_of_review)
        rvfb = review_container.find('div', class_ = 'actions text-muted').text.strip()
        feedback.append(rvfb.split('.')[0])   
    reviews = pd.DataFrame({'movie': movie_name,'reviewer': reviewer_name,'review_date': review_date,'review_title': review_titles,'review_text': review_content,'feedback': feedback})
    return reviews

In [87]:
final_reviews = pd.DataFrame()
for url in filteredimdbdata['reviewurls']:
    final_reviews = final_reviews.append(reviews(url))

In [88]:
final_reviews.head()

,movie,reviewer,review_date,review_title,review_text,feedback
0,Joker,JF500,10 September 2019,As a viewer that actually went to TIFF and wit...,I was a person that saw all the hype and claim...,"7,077 out of 8,182 found this helpful"
1,Joker,MihaVrhunc,3 October 2019,Outstanding movie with a haunting performance ...,"Every once in a while a movie comes, that trul...","3,505 out of 4,245 found this helpful"
2,Joker,lesterarnoldpinto,7 October 2019,Only certain people can relate,This is a movie that only those who have felt ...,"2,895 out of 3,620 found this helpful"
3,Joker,Aman_Goyal,1 September 2019,Perfect in every aspect.,"Truly a masterpiece, The Best Hollywood film o...","3,258 out of 4,096 found this helpful"
4,Joker,logical_guy,1 September 2019,MASTERPIECE 😍,Joaquin Phoenix gives a tour de force performa...,"2,824 out of 3,564 found this helpful"

In [89]:
final_reviews.to_csv('finalreviews.csv',index=False)